FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY {{ project_name }} ./{{ project_name }}

CMD [ "python", "-m", "{{ project_name }}" ]
