.PHONY: help requirements requirements_test lint test run destroy_db init_db destroy_mq init_mq

APP := {{ project_name }}
{%- if test %}
WORKON_HOME ?= ../.venv
VENV_BASE := $(WORKON_HOME)/aiolambda
{%- else %}
WORKON_HOME ?= .venv
VENV_BASE := $(WORKON_HOME)/${APP}
{%- endif %}
VENV_ACTIVATE := $(VENV_BASE)/bin/activate
PYTHON := ${VENV_BASE}/bin/python3

.DEFAULT: help
help:
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##/\n\t/'

venv:	## create virtualenv
	@if [ ! -d "$(VENV_BASE)" ]; then \
		virtualenv -p python3 $(VENV_BASE); \
	fi

requirements:	## install requirements
requirements: venv
	@echo Install requirements
	@${PYTHON} -m pip install -r requirements.txt > /dev/null

requirements_test:	## install test requirements
requirements_test: requirements
	@echo Install test requirements
	@${PYTHON} -m pip install -r requirements_test.txt > /dev/null

lint:	## run pycodestyle
lint: requirements_test
	@echo Running linter
	@${PYTHON} -m pycodestyle .
	@${PYTHON} -m flake8 ${APP} test
	@${PYTHON} -m mypy --ignore-missing-imports ${APP} test

test:	## run tests and show report
test: lint init_db {% if is_mq %}init_mq{% endif%}
	@echo Running tests
	@LOG_LEVEL=DEBUG ${PYTHON} -m coverage run -m pytest test
	@${PYTHON} -m coverage report -m

run:	## run project
run: requirements init_db {% if is_mq %}init_mq{% endif%}
	@${PYTHON} -m ${APP}

destroy_db:	## destroy docker database
{%- if database == 'postgresql' %}
	@echo Destroy postgres
	@docker rm -f postgres > /dev/null || echo Not postgres running
{%- endif %}

init_db:	## create docker database
init_db: destroy_db
{%- if database == 'postgresql' %}
	@echo Starting postgres
	@docker run -d --name postgres -e POSTGRES_DB=test -e POSTGRES_USER=test \
	-e POSTGRES_PASSWORD=test1234 -p 5432:5432 postgres > /dev/null
	@while ! docker exec postgres psql --host=localhost --username=test -c 'SELECT 1' >/dev/null 2>&1; do \
	 	echo 'Waiting for postgres...'; \
	 	sleep 1; \
	done;
{%- endif %}

{%- if is_mq %}
destroy_mq:    ## destroy docker mq
	@echo Destroy rabbit
	@docker rm -f rabbit > /dev/null || echo Not postgres running

init_mq:       ## create docker mq
init_mq: destroy_mq
	@echo Starting rabbit
	@docker run -d --hostname localhost --name rabbit -e RABBITMQ_DEFAULT_USER=test \
		-e RABBITMQ_DEFAULT_PASS=test1234 -p 5672:5672 rabbitmq:3 > /dev/null
	@sleep 2 # sometimes rabbitmq crash: cannot read secret cookie
	@while ! docker exec rabbit rabbitmqctl status >/dev/null 2>&1; do \
		echo 'Waiting for rabbit...'; \
		sleep 1; \
	done;
{%- endif %}
